[workspace]

members = [
    "crypto",
    "network-hypervisor",
    "controller",
    "service",
    "vl1-service",
    "utils",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
