[workspace]

members = [
  "aes-gmac-siv",
  "zerotier-core-crypto",
  "zerotier-network-hypervisor",
  "zerotier-system-service",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
