[package]
name = "zerotier-network-controller"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zerotier-controller"
path = "src/main.rs"

[dependencies]
zerotier-crypto = { path = "../crypto" }
zerotier-utils = { path = "../utils" }
zerotier-network-hypervisor = { path = "../network-hypervisor" }
zerotier-vl1-service = { path = "../vl1-service" }
serde = { version = "^1", features = ["derive"], default-features = false }
serde_json = { version = "^1", features = ["std"], default-features = false }
